### DISCUSSION TITLE
Circle CI configuration to run Cake

### DISCUSSION THREAD

**Discussion by augustoproiete** [cake-build/cake#3061] [Show and tell]
Example Circle CI configuration by @tl-ben-foster for building a .NET 5 project.

### @tl-ben-foster / config.yml

```yaml
version: 2.1

jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:5.0.102-ca-patch-buster-slim-amd64

    steps:
      - checkout
      - run: ./build.sh
```

Source: https://gist.github.com/tl-ben-foster/cc67091a312f89c9e87e7534807f2cd8
