### DISCUSSION TITLE
How to enforce TestRunner don't write to standard error?

### DISCUSSION THREAD

**Discussion by soroshsabz** [cake-build/cake#3130] [Q&A]
ITNOA

I have one task in my CI that has  `failOnStandardError: true` so when VSTest run any test that does not pass, and write standard error, I got error on CI and my pipeline is stop

My question is how to enforce test runner redirect standard error output to standard normal output?

thanks

**Comment by pascalberger** [comment]
Where have you set `failOnStandardError`. Can you please provide a sample which shows what you try to achieve.

**Reply by soroshsabz** [reply]
I have azure-pipeline yaml file like below

```
stages:
- stage: Build
  displayName: 'Build Stage'
  jobs:
  - job: Build_Windows
    displayName: 'Build .Net framework on Windows'
    workspace:
      clean: all
    steps:
    - task: BatchScript@1
      inputs:
        filename: 'Hooshang/sbuild.bat'
        arguments: '--vrebosity=diagnostic'
        workingFolder: 'Hooshang'
        failOnStandardError: true
```

And I got 

![image](https://user-images.githubusercontent.com/17947618/107879288-2743ee80-6eed-11eb-8eef-bd2789db5bbe.png)

Because VSTest says

![image](https://user-images.githubusercontent.com/17947618/107879319-64a87c00-6eed-11eb-94c6-62973b3cfdb2.png)
