### DISCUSSION TITLE
Help with powershell command for 2.0 azure devops pipeline

### DISCUSSION THREAD

**Discussion by nick5454** [cake-build/cake#3742] [Extension Q&A]
I changed my powershell script to run cake with the new 2.0, but i'm having issues.

Script
```
[CmdletBinding()]
Param(
    [string]$Script = ".\recipe.cake",
    [string]$Target,
    [string]$Configuration = "Release",
    [ValidateSet("Quiet", "Minimal", "Normal", "Verbose", "Diagnostic")]
    [string]$Verbosity = "Diagnostic",
    [switch]$ShowDescription,
    [switch]$Experimental = $true,
    [switch]$IsCore = $true,
    [Alias("WhatIf", "Noop")]
    [switch]$DryRun,
    [switch]$SkipToolPackageRestore=$false,
    [Parameter(Position=0,Mandatory=$false,ValueFromRemainingArguments=$true)]
    [string[]]$ScriptArgs

)

dotnet new tool-manifest

dotnet tool install Cake.Tool

$cakeArguments = @()
if ($Script) { $cakeArguments += "`"$Script`"" }
if ($Target) { $cakeArguments += "--target=`"$Target`"" }
if ($Verbosity) { $cakeArguments += "--verbosity=$Verbosity" }
if ($ShowDescription) { $cakeArguments += "--showdescription" }
if ($DryRun) { $cakeArguments += "--dryrun" }
$cakeArguments += $ScriptArgs

Write-Host "Running build script..."

dotnet cake $($cakeArguments -join " ")
```

yml:
```
trigger:
- master
- develop

pool:
  vmImage: 'windows-latest'

variables:
  SYSTEM_ACCESSTOKEN: $(System.AccessToken)

steps:
- powershell: .\buildcake.ps1 --Target=VSTS --Verbosity=Normal --solution=XXXXXX.sln
  displayName: Cake Build
  env:
    SYSTEM_ACCESSTOKEN: $(System.AccessToken) 
```

Diags:
```
Getting ready...
The template "Dotnet local tool manifest file" was created successfully.
You can invoke the tool from this directory using the following commands: 'dotnet tool run dotnet-cake' or 'dotnet dotnet-cake'.
Tool 'cake.tool' (version '2.0.0') was successfully installed. Entry is added to the manifest file D:\a\1\s\.config\dotnet-tools.json.
Running build script...
Error: Bootstrapping failed for 'D:/a/1/s/recipe.cake --verbosity=Diagnostic --Target=VSTS --Verbosity=Normal --solution=XXXX.sln'.
recipe.cake --verbosity=Diagnostic --Target=VSTS --Verbosity=Normal --solution=XXXX.sln, line #0: Could not find script 'D:/a/1/s/recipe.cake --verbosity=Diagnostic --Target=VSTS --Verbosity=Normal --solution=XXXX.sln'.
##[error]PowerShell exited with code '1'.
Finishing: Cake Build
```
