### ISSUE TITLE
Add convenience extensions to TextTransformationExtensions

### ISSUE THREAD

**Issue by gitfool** [cake-build/cake#2375]
I would like to add convenience extensions to TextTransformationExtension:

Support for dictionaries:

```c#
public static TextTransformation<TTemplate> WithTokens<TTemplate>(
    this TextTransformation<TTemplate> transformation, IDictionary<string, object> tokens)
    where TTemplate : class, ITextTransformationTemplate
{
    if (transformation != null && tokens != null)
    {
        foreach (var token in tokens)
        {
            if (token.Value != null) // leave placeholder for tokens without a value
            {
                transformation.Template.Register(token.Key, token.Value);
            }
        }
    }
    return transformation;
}
```
Support for shallow object properties, with optional key prefix, that feeds the first extension method:
```c#
public static Dictionary<string, object> ToTokens(this object value, string prefix = null, BindingFlags? bindingAttr = null)
{
    return value?.GetType()
        .GetProperties(bindingAttr ?? BindingFlags.Instance | BindingFlags.Static | BindingFlags.Public)
        .ToDictionary(property => string.Concat(prefix, property.Name), property => property.GetValue(value));
}
```

Thoughts? Happy to submit a PR!

**Comment by gitfool** [comment]
Here's an example of how to use the `ToTokens` convenience extension:
```c#
Task("StageManifest")
    .Does(() =>
{
    TransformTextFile(Build.Files.Manifest, "{{", "}}")
        .WithTokens(Build.Version.ToTokens("Version."))
        .Save(Build.Files.ArtifactsManifest);
});
```
where the manifest contains placeholders for `Version` properties (of type `GitVersion`):
```yaml
---
name: Test
version:
    semantic_version: {{ Version.FullSemVer }}
    assembly_version: {{ Version.AssemblySemVer }}
    assembly_file_version: {{ Version.AssemblySemFileVer }}
    informational_version: {{ Version.InformationalVersion }}
...
```
