### ISSUE TITLE
Azure Pipelines build system not recognized with non-Windows jobs

### ISSUE THREAD

**Issue by gitfool** [cake-build/cake#2432]
See the logs for all jobs in [Cake.Dungeon/#20190107.3](https://dev.azure.com/gitfool/Cake.Dungeon/_build/results?buildId=15):
- [Windows](https://dev.azure.com/gitfool/Cake.Dungeon/_build/results?buildId=15&view=logs&jobId=2d2b3007-3c5c-5840-9bb0-2b1ea49925f3&taskId=c37637b8-ed57-5a02-c556-da2855a7e2d3&lineStart=26&lineEnd=27&colStart=1&colEnd=1)
- [Linux](https://dev.azure.com/gitfool/Cake.Dungeon/_build/results?buildId=15&view=logs&jobId=0da5d1d9-276d-5173-c4c4-9d4d4ed14fdb&taskId=8ef82b3b-1feb-5bbd-06f6-b1f7b5467f03&lineStart=37&lineEnd=38&colStart=1&colEnd=1)
- [Docker](https://dev.azure.com/gitfool/Cake.Dungeon/_build/results?buildId=15&view=logs&jobId=1c8ce01e-97de-5be9-a863-648419f09741&taskId=09181c4b-3f3c-50e9-b57f-22616eaa56ea&lineStart=29&lineEnd=30&colStart=1&colEnd=1)
- [Mac](https://dev.azure.com/gitfool/Cake.Dungeon/_build/results?buildId=15&view=logs&jobId=a82d9e72-1de4-5bd6-c188-90296135479e&taskId=9cb5351e-b3b2-50c1-f66a-417115f88215&lineStart=24&lineEnd=25&colStart=1&colEnd=1) :x:

There are a couple of problems; one is that `TF_BUILD` is expected in [TFBuildProvider.cs#L46](https://github.com/cake-build/cake/blob/develop/src/Cake.Common/Build/TFBuild/TFBuildProvider.cs#L46) but is missing in the Docker job environment variables, and the other is that `AGENT_NAME` is always defined but not as expected in [TFBuildProvider.cs#L82](https://github.com/cake-build/cake/blob/develop/src/Cake.Common/Build/TFBuild/TFBuildProvider.cs#L82).

(The Mac job is currently broken for other reasons I haven't looked into yet.)

**Comment by devlead** [comment]
Wonder, is that an error in Azure Pipelines or per design?

Checking docs at https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=vsts

Variable | Description
-- | --
TF_BUILD | Set to True if the script is being run by a build task. This variable is agent-scoped. It can be used as an environment variable in a script and as a parameter in a build task, but not as part of the build number or as a version control tag.


Normally it's not available on the system but set by the process invoker on each task
https://github.com/Microsoft/azure-pipelines-agent/blob/148dbe4bb953da97a423ad899626c773371b3083/src/Agent.Sdk/ProcessInvoker.cs#L195
```csharp
            // Set the TF_BUILD env variable.
            _proc.StartInfo.Environment["TF_BUILD"] = "True";
```

Looking at the docker bits it looks like they're just copying the host variables but not setting the extra _"TF_BUILD=True"_
https://github.com/Microsoft/azure-pipelines-agent/blob/30d2e8b9c2afe9cdb98d16016968616780cea933/src/Agent.Worker/Container/DockerCommandManager.cs#L123

So likely docke process is getting the variable, but not the container itself.

@gitfool maybe worth raising an issue on agent repo to ask.

**Comment by gitfool** [comment]
@devlead Done. Re the second problem, since the `AGENT_NAME` is no longer simply `Hosted Agent`, I suggest changing the relevant part of [TFBuildProvider.IsHostedAgent](https://github.com/cake-build/cake/blob/develop/src/Cake.Common/Build/TFBuild/TFBuildProvider.cs#L79-L82) from:
```c#
_environment.GetEnvironmentVariable("AGENT_NAME") == "Hosted Agent"
```
to:
```c#
_environment.GetEnvironmentVariable("AGENT_NAME").StartsWith("Hosted")
```
Either that or switching to or also checking for the `SYSTEM_SERVERTYPE` environment variable, which I noticed has the value `Hosted` for all Azure Pipelines builds. The first option would be backwards compatible so would be preferred?

**Comment by devlead** [comment]
Isn't this from your build log?
```
2019-01-07T07:33:02.2586978Z AGENT_NAME                                                          Hosted Agent
```

**Comment by gitfool** [comment]
Yes, for the Docker job, but the other logs use different hosts.

**Comment by gitfool** [comment]
I just noticed another problem. The [TFBuildAgentInfo.MachineName](https://github.com/cake-build/cake/blob/develop/src/Cake.Common/Build/TFBuild/Data/TFBuildAgentInfo.cs#L74) is [not set](https://dev.azure.com/gitfool/Cake.Dungeon/_build/results?buildId=15&view=logs&jobId=0da5d1d9-276d-5173-c4c4-9d4d4ed14fdb&taskId=8ef82b3b-1feb-5bbd-06f6-b1f7b5467f03&lineStart=169&lineEnd=170&colStart=1&colEnd=1) - a single `"` is how I log and distinguish empty strings - as it expects the `AGENT_MACHINE_NAME` environment variable, but it [seems to be called](https://dev.azure.com/gitfool/Cake.Dungeon/_build/results?buildId=15&view=logs&jobId=0da5d1d9-276d-5173-c4c4-9d4d4ed14fdb&taskId=8ef82b3b-1feb-5bbd-06f6-b1f7b5467f03&lineStart=36&lineEnd=37&colStart=1&colEnd=1) `AGENT_MACHINENAME` instead.

**Comment by gitfool** [comment]
Okay, I'll submit a PR with those two changes...

**Comment by devlead** [comment]
@gitfool the mac build you can likely fix by adding a .NET installer task into yaml, example of such yaml 
```yaml
variables:
  DOTNET_SDK_VERSION: '2.1.502'

jobs:
- job: MacOS
  displayName: Build on MacOS

  pool:
    vmImage: 'macOS 10.13'

  steps:
  - task: DotNetCoreInstaller@0
    displayName: 'Use .NET Core SDK $(DOTNET_SDK_VERSION)'
    inputs:
      version: '$(DOTNET_SDK_VERSION)'

  - bash: ./build.sh
    displayName: 'Execute Cake Bootstrapper'

  - task: PublishTestResults@2
    displayName: 'Publish Test Results'   
    inputs:
      testRunner: xUnit
      testResultsFiles: '**/test_result.xml'
      mergeTestResults: true



- job: Windows
  displayName: Build on Windows

  pool:
    vmImage: 'VS2017-Win2016'

  steps:
  - task: DotNetCoreInstaller@0
    displayName: 'Use .NET Core SDK $(DOTNET_SDK_VERSION)'
    inputs:
      version: '$(DOTNET_SDK_VERSION)'


  - powershell: ./build.ps1
    displayName: 'Execute Cake PowerShell Bootstrapper'

  - task: PublishTestResults@2
    displayName: 'Publish Test Results'
    inputs:
      testRunner: XUnit
      testResultsFiles: '**/test_result.xml'
      mergeTestResults: true


- job: Linux
  displayName: Build on Linux

  pool:
    vmImage: 'Ubuntu 16.04'

  steps:
  - task: DotNetCoreInstaller@0
    displayName: 'Use .NET Core SDK $(DOTNET_SDK_VERSION)'
    inputs:
      version: '$(DOTNET_SDK_VERSION)'


  - bash: ./build.sh
    displayName: 'Execute Cake Bash Bootstrapper'

  - task: PublishTestResults@2
    displayName: 'Publish Test Results'
    inputs:
      testRunner: XUnit
      testResultsFiles: '**/test_result.xml'
      mergeTestResults: true


- job: Docker
  displayName: Build Docker Image

  pool:
    vmImage: 'Ubuntu 16.04'

  steps:
  - task: Docker@1
    displayName: 'Build image'
```
