### ISSUE TITLE
Add .NET Core 3 to Cake.Tool update to .NET Core 3 SDK

### ISSUE THREAD

**Issue by devlead** [cake-build/cake#2603]
* Add netcoreapp3.0 moniker to Cake.Tool
* Execute unit tests under netcoreapp3.0
* Update SDK to .NET Core 3

**Comment by myloveCc** [comment]
Please update nuget package to .NET Core 3.0!

**Comment by devlead** [comment]
> Please update nuget package to .NET Core 3.0, Thanks!
We've got an open PR ( #2604 ) which is under going final review.

Meanwhile you can use the .NET Core 2.1 tool in a pure 3.0 SDK environment by setting the environment key `DOTNET_ROLL_FORWARD_ON_NO_CANDIDATE_FX` to `2`, 2 indicates you opting in to allow rolling forward to next major release.

**Comment by RehanSaeed** [comment]
I'm having trouble running dotnet cake CLI commands on Azure Pipelines. I'm manually installing. NET Core 3.0 but getting this error when I run 'dotnet cake':

> It was not possible to find any compatible framework version
> The specified framework 'Microsoft.NETCore.App', version '2.1.0' was not found.
>  - The following frameworks were found:
>     3.0.0 at [/opt/hostedtoolcache/dotnet/shared/Microsoft.NETCore.App]
> You can resolve the problem by installing the specified framework and/or SDK.

What I don't understand is that AppVeyor still works. Do I need to wait for this upgrade to be released or is something else going on? Links to my [repo](https://github.com/RehanSaeed/Schema.NET/blob/master/azure-pipelines.yml) and [Build output](https://dev.azure.com/schema-net/Schema.NET/_build/results?buildId=245&view=logs&j=b457fee1-24b5-5b05-276f-95f55538c81f).

**Comment by devlead** [comment]
@RehanSaeed have you set environment variable `DOTNET_ROLL_FORWARD_ON_NO_CANDIDATE_FX ` to `2` to allow major roll forward?

**Comment by RehanSaeed** [comment]
No. Azure Pipelines already has older versions of. NET Core installed on their hosted build machines, so in theory I shouldn't need to right? I guess it wouldn't hurt to try.

**Comment by devlead** [comment]
Could be that the `UseDotNet@2`task installs in a non standard folder and sets path to that, because I've needed to install all SDKs I want to support something like this (if 2.0 and 2.1 needed i.e.)
```yml
steps:
- task: UseDotNet@2
  displayName: 'Use .Net Core sdk 2.1.202'
  inputs:
    version: 2.1.202

- task: UseDotNet@2
  displayName: 'Use .Net Core sdk 2.1.701'
  inputs:
    version: 2.1.701

- task: UseDotNet@2
  displayName: 'Use .Net Core sdk 3.0.100'
  inputs:
    version: 3.0.100
```
