### ISSUE TITLE
Helpers for GitHub Actions

### ISSUE THREAD

**Issue by xt0rted** [cake-build/cake#2609]
Now that GitHub Actions supports CI/CD it'd be nice to have some helpers to detect if you're running in an actions workflow like we have for other providers.

There's a list of environment variables that are set so it should be pretty straight forward to do the check and surface the basic info. https://help.github.com/en/articles/virtual-environments-for-github-actions#default-environment-variables

I'm not sure if we'll be able to setup helpers to upload artifacts (for now). There's an action for this but it seems like it references something installed on the VM instead of calling an api endpoint or writing to the log. https://github.com/actions/upload-artifact

Log messages can also be adjusted by prefixing them with `##[debug]`, `##[warning] `, and`##[error]`. This will highlight them in the build output. There's no docs on this yet, but you can see how it's done in these two files https://github.com/actions/toolkit/tree/master/packages/core/src.

> Note: the format for these just changed to `::` instead of `##` according to the comments in https://github.com/actions/toolkit/issues/57

Similar to VS Code there's also support for [problem matchers](https://code.visualstudio.com/Docs/editor/tasks#_defining-a-problem-matcher), so if we wanted to highlight specific lines from cake's output we could do that by bundling those files alongside cake and registering them if we're in an actions workflow. This could be useful for highlighting the version of cake being used, or any warnings it may give about mismatched versions.

I'm slowly migrating all of my builds over to actions so I'm happy to help add this in and test it.

**Comment by devlead** [comment]
Agreed,  this would be something we would want to support.

**Comment by gep13** [comment]
@xt0rted do you have any examples of projects which you are porting to GitHub Actions CI/CD?

**Comment by xt0rted** [comment]
@gep13 I don't have any public .net projects right now, but I could setup a test one if you'd like.

Here's [the workflows](https://github.com/xt0rted/block-autosquash-commits-action/tree/actions-v2/.github/workflows) for a node action I'm migrating along with [the build output](https://github.com/xt0rted/block-autosquash-commits-action/pull/26/checks).

This is one of my master branch workflows that's building, packaging, and publishing to azure app services. It's being published as s self-contained app so it's using the Windows VM but it could also use Ubuntu or OSX.

```yaml
name: master

on:
  push:
    branches: master

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@master

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          version: 3.0.100-preview8-013656

      - name: Build Site
        run: dotnet build --configuration Release

      - name: Publish Site To Artifacts Folder
        env:
          DOTNET_CONFIGURE_AZURE: 1
        run: dotnet publish --configuration Release --output artifacts

      - name: Package Artifacts
        run: Compress-Archive -Path artifacts\* -DestinationPath artifacts
        shell: powershell

      - name: Publish Artifacts
        uses: actions/upload-artifact@v1
        with:
          name: artifacts.zip
          path: artifacts.zip

      - name: Publish To Azure
        uses: azure/appservice-actions/webapp@master
        with:
          app-name: app-name
          package: artifacts.zip
          publish-profile: ${{ secrets.azureWebAppPublishProfile }}
```

**Comment by gep13** [comment]
@xt0rted thanks for that!  An example would be good.  I am just curious about "how" Cake is being used in the wild with regard to GitHub Actions CI/CD, to better understand how we can support it, i.e. where it makes sense to get involved, what we leave up to the consumer, etc.

**Comment by devlead** [comment]
Guess anything after `Setup .NET Core` could be replaced with 
```sh
dotnet tool install -g Cake.Tool
dotnet cake
```
which we probably could provide a GitHub action for that would work xplat.

**Comment by xt0rted** [comment]
@gep13 I'll be moving projects from both AppVeyor and Azure DevOps. In those builds I'm using the following:

```csharp
var buildNumber = EnvironmentVariable<int>("BUILD_BUILDID", 0);
var prNumber = EnvironmentVariable<int>("SYSTEM_PULLREQUEST_PULLREQUESTNUMBER", 0);

Task("PatchAssemblyInfo")
    .WithCriteria(TFBuild.IsRunningOnAzurePipelinesHosted)
    .Does(() => { ... });
```

```csharp
var buildNumber = EnvironmentVariable<int>("APPVEYOR_BUILD_NUMBER", 0);

var prNumber = EnvironmentVariable("APPVEYOR_PULL_REQUEST_NUMBER");

if (AppVeyor.IsRunningOnAppVeyor)
{
    AppVeyor.UpdateBuildVersion(version);
}

Information($"Build version: {version}");
Information($"Version suffix: {versionSuffix}");
```

The main thing I was thinking about carrying over was a check to see if you're running in an action, along with the other environment variables where appropriate. You can also access the full json payload that triggered the workflow by reading the file from the `GITHUB_EVENT_PATH` env var. That can have more info like PR number, etc.

I don't think actions themselves are really relevant to Cake, they're just another build platform to surface information from.

You can run scripts as job steps now so to call your build script it's as simple as:

```yaml
steps:
  - name: Build Project
    run: ./build.ps1
    shell: powershell
```

If an action uses a Docker container then it always runs on Linux regardless of the host OS, so I don't think there's need for a Cake action like the DevOps task. Maybe a Javascript based action could work but when you can call the script so easily it seems like a lot of work for little gain.
