### ISSUE TITLE
IsRunningOnAzurePipelines doesn't work for Ubuntu

### ISSUE THREAD

**Issue by matt40k** [cake-build/cake#3148]
### What You Are Seeing?

IsRunningOnAzurePipelines returns false

### What is Expected?

IsRunningOnAzurePipelines returns true

### What environment are you running on?  Windows? Linux? Mac?

Linux

### Are you running on a CI Server?  If so, which one?

Azure Pipelines

### How Did You Get This To Happen? (Steps to Reproduce)

https://cakebuild.net/docs/integrations/build-systems/azure-pipelines/

```
if (BuildSystem.AzurePipelines.IsRunningOnAzurePipelines)
{
	Information("Running on AzurePipelines");
}
```

```
trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: cake-build.cake.cake-build-task.Cake@2
  displayName: 'Cake build'
  inputs:
    script: build/build.cake
    target: CI

```

### Output Log
Nothing
